routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Models\Document;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/pdf', function () {
    return view('pages.contract.pdf', [
        'document' => Document::first()
    ]);
});

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
    // User
    Route::resource('user', UserController::class);

    // Document
    Route::get('/document', [App\Http\Controllers\DocumentController::class, 'index'])->name('document.index');
    Route::get('/document/{document}', [App\Http\Controllers\DocumentController::class, 'show'])->name('document.show');
    Route::post('/document/{document}/approve', [App\Http\Controllers\DocumentController::class, 'approve'])->name('document.approve');
    Route::post('/document/{document}/reject', [App\Http\Controllers\DocumentController::class, 'reject'])->name('document.reject');

    // History
    Route::get('/history', [App\Http\Controllers\HistoryController::class, 'index'])->name('history.index');
    Route::get('/history/{document}', [App\Http\Controllers\HistoryController::class, 'show'])->name('history.show');

    // Contract
    Route::get('/contract', [App\Http\Controllers\ContractController::class, 'index'])->name('contract.index');
    Route::get('/contract/{document}', [App\Http\Controllers\ContractController::class, 'show'])->name('contract.show');
    Route::get('/contract/{document}/pdf', [App\Http\Controllers\ContractController::class, 'exportPdf'])->name('contract.pdf');

    // Profile
    Route::get('/profile', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile.index');
    Route::post('/profile', [App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
});

// Dashboard
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DataTables;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()){
            $query = User::query()
                ->where('id', '!=', Auth::id());

            return DataTables::of($query)
                ->editColumn('action', function ($model) {
                    $response = "
                    <div class='text-center'>
                        <a href='".route('user.edit', $model['id'])."' class='btn btn-sm btn-light-success btn-circle btn-icon mr-2' title='Edit'><i class='fas fa-pen icon-nm'></i></a>
                        <a href='".route('user.destroy', $model['id'])."' class='btn btn-sm btn-light-danger btn-circle btn-icon mr-2 btn-delete' title='Delete'><i class='fas fa-trash-alt icon-nm'></i></a>
                    </div>";

                    return $response;
                })
                ->make(true);
        }

        return view('pages.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.user.create', [
            'roles' => Role::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'      => 'required',
            'email'     => 'required|email',
            'password'  => 'required|confirmed',
            'role'      => 'required'
        ]);

        DB::beginTransaction();
        try {
            $user = User::create([
                'name'      => $request->name,
                'email'     => $request->email,
                'password'  => Hash::make($request->password)
            ]);

            $user->assignRole([$request->role]);

            DB::commit();
        }catch (\Exception $e){
            DB::rollBack();
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('user.index')->withMessage('Add user successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|void
     */
    public function edit(User $user)
    {
        return view('pages.user.edit', [
            'data' => $user,
            'roles' => Role::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'  => 'required',
            'email'  => 'required',
        ]);

        DB::beginTransaction();

        try {
            $user->update([
                'name'      => $request->name,
                'email'     => $request->email,
            ]);

            $user->syncRoles([$request->role]);
        }catch (\Exception $e){
            DB::rollBack();
            return back()->withErrors($e->getMessage())->withInput();
        }

        if (isset($request->password) && !empty($request->password)){
            $request->validate([
                'password'  => 'required|min:6|confirmed'
            ]);

            $user->update([
                'password'  => Hash::make($request->password)
            ]);
        }

        DB::commit();
        return redirect()->route('user.index')->withMessage('Update user successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User $user)
    {
        try {
            $user->delete();
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage());
        }

        return back()->withMessage('Delete user successfully');
    }

    public function updateProfile(Request $request)
    {
        try {
            $this->userService->updatePersonalData($request->except('_token'), Auth::user());
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return back()->withMessage('Update personal information successfully');
    }

    public function updatePersonalPassword(Request $request)
    {
        try {
            $this->userService->changePersonalPasswordUser($request->except('_token'), Auth::user());
        }catch (\Exception $e){
            return back()->withErrors($e->getMessage())->withInput();
        }

        return redirect()->route('profile.show')->withMessage('Update personal information successfully');
    }
}

resources/views/pages/user/create.blade.php
@extends('layouts.master')
@section('title', 'Add New User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Add New User</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <a href="" class="text-muted">User</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Add New</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card card-custom">
            <div class="card-header flex-wrap">
                <div class="card-title">
                    <h3 class="card-label">Add New</h3>
                </div>
            </div>

            <div class="card-body">
                <form action="{{ route('user.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old('name') }}" required autocomplete="new-name"/>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" placeholder="Email" name="email" value="{{ old('email') }}" autocomplete="new-email" required/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Role</label>
                                <select class="form-control select2" id="role" name="role" style="width: 100%" required>
                                    <option value="" selected disabled></option>
                                    @foreach ($roles as $role)
                                        <option value="{{ $role->name }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-12">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" placeholder="Password" name="password" value="" autocomplete="new-password" required/>
                            </div>
                        </div>
                        <div class="col-sm-6 col-12">
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input type="password" class="form-control" placeholder="Confirm Password" name="password_confirmation" value="" required/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-success btn-block">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js-script')
<script>
    $('#role').select2({
        placeholder: 'Select Role',
        allowClear: true
    });
</script>
@endpush

resources/views/pages/user/edit.blade.php
@extends('layouts.master')
@section('title', 'Edit User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Edit User</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <a href="" class="text-muted">User</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">Edit</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
<div class="row justify-content-center">
    <div class="col-12">
        <div class="card card-custom">
            <div class="card-header flex-wrap">
                <div class="card-title">
                    <h3 class="card-label">Edit</h3>
                </div>
            </div>

            <div class="card-body">
                <form action="{{ route('user.update', $data) }}" method="POST" enctype="multipart/form-data">
                    @csrf @method('PATCH')
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" name="name" value="{{ old('name') ?? $data->name }}" required autocomplete="new-name"/>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" placeholder="Email" name="email" value="{{ old('email') ?? $data->email }}" autocomplete="new-email" required/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label>Role</label>
                                <select class="form-control select2" id="role" name="role" style="width: 100%" required>
                                    <option value="" selected disabled></option>
                                    @foreach ($roles as $role)
                                        <option value="{{ $role->name }}" {{ $data->hasRole($role->name) ? 'selected' : '' }}>{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="separator separator-dashed my-10"></div>
                            <h4>Change Password</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-12">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" placeholder="Password" name="password" value="" autocomplete="new-password"/>
                            </div>
                        </div>
                        <div class="col-sm-6 col-12">
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input type="password" class="form-control" placeholder="Confirm Password" name="password_confirmation" value=""/>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-success btn-block">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js-script')
<script>
    $('#role').select2({
        placeholder: 'Select Role',
        allowClear: true
    });
</script>
@endpush

resources/views/pages/user/index.blade.php
@extends('layouts.master')
@section('title', 'List User')

@section('breadcumb')
    <!--begin::Page Title-->
    <h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Lists</h5>
    <!--end::Page Title-->
    <!--begin::Actions-->
    <div class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
    <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
        <li class="breadcrumb-item">
            <a href="" class="text-muted">User</a>
        </li>
        <li class="breadcrumb-item">
            <span class="text-muted">List</span>
        </li>
    </ul>
    <!--end::Actions-->
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <!--begin::Mixed Widget 10-->
        <div class="card card-custom">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">
                <div class="card-title">
                    <h3 class="card-label">List User</h3>
                </div>
                <div class="card-toolbar">
                    <!--begin::Button-->
                    <a href="{{ route('user.create') }}" class="btn btn-success font-weight-bolder">
                    <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24"/>
                                <circle fill="#000000" cx="9" cy="15" r="6"/>
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3"/>
                            </g>
                        </svg>
                        <!--end::Svg Icon-->
                    </span>Add new
                    </a>
                    <!--end::Button-->
                </div>
            </div>

            <div class="card-body">
                <table class="table table-separate table-head-custom table-checkable" id="datatable">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>

            </div>
        </div>
        <!--end::Mixed Widget 10-->
    </div>
</div>
@endsection

@push('js-script')
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable({
                scrollX: true,
                processing: true,
                serverSide: true,
                ajax: "{{ route('user.index') }}",
                columns: [
                    {data: null, sortable: false, searchable: false,
                        render: function (data, type, row, meta) {
                            return meta.row + meta.settings._iDisplayStart + 1;
                        }
                    },
                    {data: 'name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ]
            })
        });
    </script>
@endpush